-- to set the debug level add the following to your server.cfg
-- set ox:printlevel:<resourceName> "<level>"
-- levels are: error, warn, info, debug
-- default level is info or edit it inside of server/debug.lua